{% set name = "piqp" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PREDICT-EPFL/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d34f98a639b01c22b1c2f99bc42e3c5865b661151531525e873697b149cd2583

build:
  skip: true  # [win and vc<14]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - make  # [not win]
    - ninja
    - cmake >=3.12
  host:
    - setuptools >=42
    - wheel
    - eigen
    - libmatio
    - python
    - pip
  run:
    - eigen
    - libmatio
    - python

test:
  imports:
    - piqp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PREDICT-EPFL/piqp
  doc_url: https://predict-epfl.github.io/piqp/
  summary: A Proximal Interior Point Quadratic Programming solver
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RSchwan
